/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#131313",
        surface: "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "deep-void": "#000000",
        "stadium-white": "#FFFFFF",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#bfc7d2",
        "on-background": "#e5e2e1",
        outline: "#89929c",
        "outline-variant": "#3f4850",
        primary: "#93ccff",
        "primary-container": "#2c98de",
        "primary-fixed": "#cde5ff",
        "on-primary": "#003352",
        "on-primary-container": "#002c47",
        secondary: "#4edea3",
        "secondary-container": "#00a572",
        "on-secondary": "#003824",
        tertiary: "#ffb869",
        "tertiary-container": "#cd7f0d",
        "on-tertiary": "#482900",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
      },
      fontFamily: {
        display: ["Anton", "sans-serif"],
        body: ["'Hanken Grotesk'", "sans-serif"],
        mono: ["'Space Mono'", "monospace"],
      },
      fontSize: {
        "display-xl": [
          "120px",
          { lineHeight: "110px", letterSpacing: "-0.02em", fontWeight: "400" },
        ],
        "display-lg": [
          "80px",
          { lineHeight: "76px", letterSpacing: "-0.01em", fontWeight: "400" },
        ],
        "display-md": [
          "48px",
          { lineHeight: "44px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "headline-lg": [
          "48px",
          { lineHeight: "52px", letterSpacing: "0.02em", fontWeight: "400" },
        ],
        "headline-md": [
          "32px",
          { lineHeight: "36px", letterSpacing: "0.02em", fontWeight: "400" },
        ],
        "headline-sm": [
          "22px",
          { lineHeight: "28px", letterSpacing: "0.02em", fontWeight: "400" },
        ],
        marquee: ["64px", { lineHeight: "1", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px" }],
        "body-md": ["16px", { lineHeight: "24px" }],
        "body-sm": ["14px", { lineHeight: "20px" }],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.12em", fontWeight: "700" },
        ],
        "label-caps-lg": [
          "14px",
          { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" },
        ],
      },
      borderRadius: {
        DEFAULT: "0px",
        sm: "2px",
        md: "4px",
        lg: "6px",
        full: "9999px",
      },
      boxShadow: {
        hard: "8px 8px 0px 0px #93ccff",
        "hard-secondary": "8px 8px 0px 0px #4edea3",
        "hard-tertiary": "8px 8px 0px 0px #ffb869",
        "hard-white": "8px 8px 0px 0px #FFFFFF",
        "hard-sm": "4px 4px 0px 0px #93ccff",
        "hard-lg": "12px 12px 0px 0px #93ccff",
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 20px #4edea3" },
          "50%": { boxShadow: "0 0 40px #4edea3, 0 0 60px #4edea3" },
        },
      },
      animation: {
        marquee: "marquee 30s linear infinite",
        "marquee-rev": "marquee 30s linear infinite reverse",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
